# Generated by Django 3.2.10 on 2022-08-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='total_expense',
        ),
    ]
