# Generated by Django 3.2.10 on 2022-08-05 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_alter_basket_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
